---
steps:

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - .
      - -t
      - gcr.io/$PROJECT_ID/gradle_w_zulu_jdk_6_7_8_9
      - --cache-from
      - gcr.io/$PROJECT_ID/gradle_w_zulu_jdk_6_7_8_9

images:
  - gcr.io/$PROJECT_ID/gradle_w_zulu_jdk_6_7_8_9
