---
steps:

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - .
      - -t
      - gcr.io/$PROJECT_ID/bunches
      - --cache-from
      - gcr.io/$PROJECT_ID/bunches

images:
  - gcr.io/$PROJECT_ID/bunches
